import re
from typing import List

def clean_ocr_text(raw_text: str) -> str:
    if not raw_text:
        return ""
    
    # Remove unprintable control characters (often generated by bad OCR)
    # but keep standard newlines and tabs
    text = re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]', '', raw_text)
    
    # Replace sequences of 2 or more spaces with a single space
    text = re.sub(r' {2,}', ' ', text)
    
    # Replace sequences of 3 or more newlines with just 2 newlines (preserves paragraphs)
    text = re.sub(r'\n{3,}', '\n\n', text)
    
    return text.strip()

def chunk_text(text: str, chunk_size: int = 1500, overlap: int = 200) -> List[str]:
    if not text:
        return []
    
    chunks = []
    start = 0
    text_length = len(text)
    
    while start < text_length:
        # Calculate the end index for this chunk
        end = start + chunk_size
        
        # Extract the chunk and add it to the list
        chunk = text[start:end]
        chunks.append(chunk)
        
        # Move the start pointer forward, subtracting the overlap
        # to ensure context isn't lost between chunks
        start += (chunk_size - overlap)
        
    return chunks